name: reloadly
description: Reloadly Dart Sdk.It wraps the reloadly airtime sdk.Helps you generate tokens, get your balance and topup any number in the world.
version: 1.0.5
homepage: https://harambeeapps.co.ke
repository: https://github.com/cosmasken/reloadly

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  dio: ^4.0.0


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
